### ISSUE TITLE
博客写的和gethub代码不一样，你是在开玩笑？

### ISSUE THREAD

**Issue by fffkaa** [owen-jia/cloud-parent#1]

**Comment by owen-jia** [comment]
哪里不一样呢？

**Comment by fffkaa** [comment]
你有毛病


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "owen-jia/cloud-parent"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月14日(星期三) 上午10:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [owen-jia/cloud-parent] 博客写的和gethub代码不一样，你是在开玩笑？ (Issue #1)





 
哪里不一样呢？
